### ISSUE TITLE
Feature request: Incorporate no-undoc-members from autodoc

### ISSUE THREAD

**Issue by wynn-rj** [speedyleion/sphinx-c-autodoc#10]
I want to start out with saying that this is a great tool and it is making the generation of documentation much better and easier. 

My use case for this extension has been to generate documentation automatically from documented source code. The idea being that developers should have to put no effort in beyond commenting their code to get documentation for it. One constraint I have found is that sphinx will emit a warning for duplicate member declarations across different files, which will commonly occur in a c project where the prototypes for functions are declared in header files. If the prototypes are declared within the same file, clang will correctly ignore the prototype, but it will not do this when the prototype is in a separate file. I would suggest adding a feature where prototypes declared within a header file with no documentation should either be skipped completely, or at least made private. This would allow a developer to still use the `autocmodule` directive to not have to manually define what elements from a header they would want to have to avoid including a prototype. 

Below is a simple way of implementing this
```py
class DocumentedFunction(DocumentedObject):
    ...
    def is_public(self) -> bool:
        """
        Functions are public as long as they are not static.
        """
        # Start of changes
        if self.node.location.file.name.endswith(".h") \
                and not self.node.is_definition() \
                and self.doc == "":
            return False
        # End of changes

        if self.node.storage_class == StorageClass.STATIC:
            return False

        return True
```

This implementation could be expanded to be dependent on a configuration variable being set (I'm not very familiar with writing sphinx extensions and didn't see how to access the environment from this class or I would have included this above, sorry!).

An alternative option to this would be to implement the meta tag features present in sphinx's autodoc to allow the developer to set if something is private within a comment (using `:meta private:`). While this feature is useful I believe the above feature will be more easily adopted and easier to use by the end developer.

If you would like me to make a PR for this issue just let me know and I can do that. Sorry for all the issues recently! 😆

**Comment by speedyleion** [comment]
>The idea being that developers should have to put no effort in beyond commenting their code to get documentation for it.
I agree, try to make it as automatic for the majority of cases, but still overridable for those that want customization.

>One constraint I have found is that sphinx will emit a warning for duplicate member declarations across different files
One idea I've been trying to consider, is doing like doxygen and combining the documentation from the declaration and the definition.  I think it would require an option to let the user specify if the docs go at the declaration or the definition location. 

>I would suggest adding a feature where prototypes declared within a header file with no documentation should either be skipped completely
I wonder if this specific instance might be better served by bringing in the [no-undoc-members](https://www.sphinx-doc.org/en/master/usage/extensions/autodoc.html) from autodoc.  
I think this would be a bit more robust than the no doc == private, in case someone still wants to document private, but not document undocumented members.  Thinking static module variables or defines.  
I need to check, but I think right now in its current form the extension will try to document header include guards.
```
#ifndef MY_INCLUDE_GUARD
#define MY_INCLUDE_GUARD  // <-- I think this shows up in header docs
```

I didn't know about the meta tags, thanks for sharing that. I agree for the current use case the meta tags might too much manual work on the documentation writers.

>If you would like me to make a PR for this issue just let me know and I can do that
That's up to you if you want to do a PR.  I don't think I've done a good job of documenting the tests, so it would be interesting what your take is on them and how easy or not you find them to extend. 

> Sorry for all the issues recently
I'm excited you you're both using the extension and taking the time to point out flaws and propose improvements.  Even though C is a _smaller_ language than some, the practices people have vary quite widely and it's good to hear how this could be improved to support others.

**Comment by wynn-rj** [comment]
> One idea I've been trying to consider, is doing like doxygen and combining the documentation from the declaration and the definition. I think it would require an option to let the user specify if the docs go at the declaration or the definition location.

I think adding something like this would be incredibly useful, especially if also integrated with the `viewsource` extension, which would allow the developer to define the documentation in a header file, have it show up in the source (or header) and have it link to the source code.

> I need to check, but I think right now in its current form the extension will try to document header include guards.

I can confirm that it will document header guards

> I'm excited you're both using the extension and taking the time to point out flaws and propose improvements.  Even though C is a smaller language than some, the practices people have vary quite widely and it's good to hear how this could be improved to support others.

I'm glad to hear you are excited. I'm glad that you are interested in making this a really useful tool and are willing to apply my finding from my particular use cases.

**Comment by wynn-rj** [comment]
I redefined the issue to better address the requested feature based off of this comment
> I wonder if this specific instance might be better served by bringing in the no-undoc-members from autodoc.
I think this would be a bit more robust than the no doc == private, in case someone still wants to document private, but not document undocumented members. Thinking static module variables or defines.

After working more with this extension this is much more along the lines of what I am looking for than my original request
