### ISSUE TITLE
undefined symbol: clang_CXXMethod_isDeleted

### ISSUE THREAD

**Issue by franz-ms-muc** [speedyleion/sphinx-c-autodoc#121]
https://github.com/sphinx-doc/sphinx/issues/11302

### Describe the bug

see this Log: 

https://readthedocs.org/api/v2/build/20050480.txt

### How to Reproduce

see:

https://github.com/Meisterschulen-am-Ostbahnhof-Munchen/visual-programming-languages-docs/blob/main/docs/conf.py

### Environment Information

```text
all Settings public Available:

https://github.com/Meisterschulen-am-Ostbahnhof-Munchen/visual-programming-languages-docs
```

https://github.com/sphinx-doc/sphinx/issues/11302

**Comment by speedyleion** [comment]
Thanks for that log! It really helps.
It looks like a clang mismatch. You're not the first to run into this :(. I think `cindex.py` (thus the clang python package) should get patched to ensure that it's version is <= the libclang version.

Anyway the mismatch:
```console
Setting up libclang-common-14-dev (1:14.0.0-1ubuntu1) ...
Setting up clang-14 (1:14.0.0-1ubuntu1) ...
```

```console
Collecting clang
  Downloading clang-16.0.1.1-py3-none-any.whl (31 kB)
```
The log looks like it's installing libclang 14, but using version 16.0.1.1 of the python clang package, https://pypi.org/project/clang/
Looks like `clang_CXXMethod_isDeleted` is new in clang/llvm 16, https://reviews.llvm.org/D133924

Looking at https://github.com/Meisterschulen-am-Ostbahnhof-Munchen/visual-programming-languages-docs/blob/main/docs/requirements.txt, I'm thinking the following should work around this issue on the read the docs.
```diff
- clang
+ clang <= 14
```

**Comment by speedyleion** [comment]
and looking at the sphinx issue it seems my read the docs build for mainline are borked too

**Comment by franz-ms-muc** [comment]
[https://readthedocs.org/projects/visual-programming-languages-docs/builds/20068644/](https://readthedocs.org/projects/visual-programming-languages-docs/builds/20068644/)

run a Test.

**Comment by franz-ms-muc** [comment]
> Looking at https://github.com/Meisterschulen-am-Ostbahnhof-Munchen/visual-programming-languages-docs/blob/main/docs/requirements.txt, I'm thinking the following should work around this issue on the read the docs.
> 
> ```diff
> - clang
> + clang <= 14
> ```

[https://readthedocs.org/api/v2/build/20068644.txt](https://readthedocs.org/api/v2/build/20068644.txt)

this worked !
