### ISSUE TITLE
Bug: Variable types from standard includes can cause warnings

### ISSUE THREAD

**Issue by wynn-rj** [speedyleion/sphinx-c-autodoc#13]
Any file level variable that has a type that is included from a standard include file (such as `bool` from `<stdbool.h>` or `pthread_mutex_t` from `<pthread.h>`) will cause the following error to be emitted
```
/usr/local/lib/python3.7/dist-packages/sphinx_c_autodoc-0.3.1-py3.7.egg/sphinx_c_autodoc/loader.py:docstring of example.c:1: WARNING: Error in declarator or parameters
Invalid C declaration: Expected identifier in nested name. [error at 3]
```
And the documentation generated from them will be incorrect. No type will be listed and the `[source]` link if using the viewcode extension will not be present. 

After a little inspection it seems to be that the issue arises whenever the `get_soup_declaration` method of the `DocumentVariable` class returns `None`. It then defaults to using the name of the variable, which is without a type. A possible place to get the correct type information from would be the `node.get_tokens()` method, but there may be a better place that I am not aware of

The following bug can be replicated by including the following code into `example.c`
```c
#include <stdbool.h>

/** 
 * A file level bool variable
 */
bool some_bool_variable = true;

**Comment by speedyleion** [comment]
Good find, the fall back logic should definitely handle this nicer.
Probably need to do as you suggested and walk the tokens, there is similar logic for function signatures.

FYI, I can't recall how clang works on *nix, but if it's not finding the standard libs, it probably needs the library paths explicitly passed, which can be done with [c-autodoc-compilation-database](https://sphinx-c-autodoc.readthedocs.io/en/latest/configuration.html?highlight=compilation#c-autodoc-compilation-database)
