### ISSUE TITLE
Un-named typedef structs yield invalid signature warning in 1.2.0

### ISSUE THREAD

**Issue by brittanyb** [speedyleion/sphinx-c-autodoc#166]
Just ran a build with 1.2.0 this morning on a project using sphinx-c-autodoc that yielded a warning:
``invalid signature for autocstruct (path/file.h::)``

This is caused by this style of unnamed declaration:
```
typedef struct
{
    int foo;
    int bar;
} struct_def_t;
```

and not :

```
typedef struct named
{
    int foo;
    int bar;
} struct_def_t;
```

The error doesn't disappear with any changes to documentation of the struct, and I can confirm that the issue is not present in further builds using 1.1.0 releases.

**Comment by speedyleion** [comment]
Thanks for the small test case to use.
Sounds like my clang 16 changes weren't as good as I thought :(, sorry about that.

Do you happen to know which version of the libclang binary you're using?

**Comment by brittanyb** [comment]
No need to apologise. I'm very thankful for your work. :) 

Primarily, we're using clang 6.0.0.2 (though this will change as it gets deprecated in modules that depend on it). I can see that the same issue is present when building with 10.0.1 and 14.0 also, so I do believe it's independent of the clang version.
