### ISSUE TITLE
Sphinx-c-autodoc v1.3.0 release

### ISSUE THREAD

**Issue by lvthanh03** [speedyleion/sphinx-c-autodoc#204]
Is this something on the roadmap for being released soon? We would love to have compability/support with Sphinx7 so we're awaiting this release.

Thanks!

**Comment by speedyleion** [comment]
Thanks so much for prodding on this.  
I missed the fact that I updated to sphinx 7, but never released that update for it.
Will see about getting one out shortly

**Comment by speedyleion** [comment]
It's released now, https://pypi.org/project/sphinx-c-autodoc/1.3.0/

**Comment by lvthanh03** [comment]
Thank you for the release!
