### ISSUE TITLE
Enums are namespaced, and rendered as such

### ISSUE THREAD

**Issue by polwel** [speedyleion/sphinx-c-autodoc#7]
In C, when I document the various options of an `enum`, sphinx-c-autodoc puts them in a namespace named after the enum. When x-referencing the enumerators, I need to provide the namespace. That is okay I guess for writing the documentation (explicit and all), but the namespace actually ends up in the rendered output. This is contrary to how the languages (C & C++) work; they consider the enumerators to live in the same namespace as the enum itself. C doesn't even have namespaces to begin with.

```C
typedef enum MYAPI_ErrorCode {
    /**
     * No error
     */
    MYAPI_STATUS_SUCCESS = 0,
} MYAPI_ErrorCode ;

/**
 * :returns: :c:enumerator:`MYAPI_ErrorCode.MYAPI_STATUS_SUCCESS`
 */
MYAPI_ErrorCode foobar();
```

Rendered:

![image](https://user-images.githubusercontent.com/7679808/94459676-fe2df600-01b7-11eb-8015-52b60df15519.png)

**Comment by speedyleion** [comment]
Thanks for the detailed description.

This might have changed with the recent sphinx 3 migration. Where I work we mainly use anonymous enums and it seems like full  _namespacing_ would make those difficult to reference.

I'll have to do some investigating, but for now I agree this should be improved

For named enums you should be able to work around this by prefixing the name with `~`.  See https://www.sphinx-doc.org/en/3.x/usage/restructuredtext/roles.html#cross-referencing-syntax for more info.

**Comment by speedyleion** [comment]
@polwel ,
I don't suppose you can provide the versions of your sphinx environment.

I tried reproducing.  Anonymous, named, and typedefed enums are all linking locally with just the enumerator name.  The URL shows the full `c.enum.enumerator` 

my setup for reference.

Packages:
```
Sphinx==3.2.1
sphinx-c-autodoc==0.3.0
sphinx-rtd-theme==0.5.0
sphinxcontrib-applehelp==1.0.2
sphinxcontrib-devhelp==1.0.2
sphinxcontrib-htmlhelp==1.0.3
sphinxcontrib-jsmath==1.0.1
sphinxcontrib-qthelp==1.0.3
sphinxcontrib-serializinghtml==1.1.4
```
The current extensions on are:
```
sphinx.ext.imgmath
sphinx.ext.viewcode
sphinx.ext.autosectionlabel
sphinx.ext.graphviz
sphinx_c_autodoc
```

Windows box, python 3.7.4, defaulting to c domain.

The current thing I might try is not defaulting to c domain. I did try the role with and without domain, as well as using returns like you had.

**Comment by polwel** [comment]
Thanks a lot for looking into this. I have created a full minimal example that shows the issue for me. I've also included a `freeze.txt` that shows my python environment. I am using Python 3.8.5, AMD64 on Windows. Installed as an anaconda environment.

[docs_enum_test.zip](https://github.com/speedyleion/sphinx-c-autodoc/files/5304684/docs_enum_test.zip)

**Comment by polwel** [comment]
Uhh... I did `make clean`, rebuilt, and now it is working...

**Comment by speedyleion** [comment]
Ok so you think you found the problem, that's good.  Prior to your edit I was thinking perhaps an incremental issue.

I do appreciate you taking the time to report, and if you think enum vs enumerator might belong in the, currently non existent, faq or similar let me know.
