### ISSUE TITLE
Incorrect minimum sphinx version

### ISSUE THREAD

**Issue by wynn-rj** [speedyleion/sphinx-c-autodoc#8]
In [setup.py](../blob/master/setup.py), the minimum required version for sphinx is `>= 3`. However, `sphinx-c-autodoc` does not work with this version, as it depends on features added in the `3.1.0` version of sphinx. Setting the minimum version to `>= 3.1` fixes the issue

```
Traceback (most recent call last):
  File "/usr/local/bin/sphinx-c-apidoc", line 6, in <module>
    from sphinx_c_autodoc.apidoc import main
  File "/usr/local/lib/python3.7/dist-packages/sphinx_c_autodoc/__init__.py", line 29, in <module>
    from sphinx.ext.autodoc import (
ImportError: cannot import name 'member_order_option' from 'sphinx.ext.autodoc' (/usr/local/lib/python3.7/dist-packages/sphinx/ext/autodoc/__init__.py)
```

**Comment by speedyleion** [comment]
Thank you for taking the time to report this issue as well as lock down the _real_ minimum version.

It looks like this relates to https://github.com/sphinx-doc/sphinx/pull/7676 which is marked as a bug.
Given that, I'm going to just bump the min version to `3.1` as you mentioned.
