### ISSUE TITLE
Viewcode extension crashes if code listing has no children

### ISSUE THREAD

**Issue by wynn-rj** [speedyleion/sphinx-c-autodoc#9]
[`_insert_line_anchors`](https://github.com/speedyleion/sphinx-c-autodoc/blob/master/src/sphinx_c_autodoc/viewcode/__init__.py#L241) does not check to see if key `"children"` exists before iterating through it's members. This is caused by empty c files or header files that have no normal members. An example would be a header file like this
```c
/* version_list.h */
"version_1",
"version_2",
```
Which would be included in a c file like
```
char * supported_versions[] {
    #include "version_list.h"
}
```

**Comment by speedyleion** [comment]
Thanks for pointing this out. Even though it looks to be pretty light I may not have time to get to this for a few days.
